### ISSUE TITLE
镜像中的horovod报错 

### ISSUE THREAD

**Issue by zzhao1998** [iiisthu/gpupool#14]
Framework: pytorch
Image:172.16.112.220:30006/library/ubuntu-pytorch:1.5.0
gloo 0.1.2

command:horovodrun -np 4 -H localhost:4 python run_roberta.py

`Traceback (most recent call last):
  File "/usr/local/bin/horovodrun", line 21, in <module>
    run_commandline()
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/run.py", line 876, in run_commandline
    _run(args)
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/run.py", line 844, in _run
    _launch_job(args, remote_host_names, settings, common_intfs, command)
  File "/usr/local/lib/python3.6/dist-packages/horovod/run/run.py", line 854, in _launch_job
    if not gloo_built(verbose=(settings.verbose >= 2)):
  File "/usr/local/lib/python3.6/dist-packages/horovod/common/util.py", line 110, in wrapper
    retval = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/horovod/common/util.py", line 143, in gloo_built
    raise RuntimeError('Failed to determine if Gloo support has been built. '
RuntimeError: Failed to determine if Gloo support has been built. Run again with --verbose for more details.
`
查了一下，可能是horovod没有配置好的缘故
https://github.com/horovod/horovod/issues/1831
可以通过重新安装horovod，需要在安装时指定mpi或gloo

**Comment by fingertap** [comment]
基于orion的原始镜像（查看[镜像列表](https://github.com/iiisthu/gpupool/blob/master/usage.md#%E9%95%9C%E5%83%8F%E5%88%97%E8%A1%A8)中的`orion-client-2.4.2`），安装好horovod后打成自己的镜像。基于orion的自建镜像需要安装orion修改后的pytorch或tensorflow，具体方式见[FAQ](https://github.com/iiisthu/gpupool/blob/master/faq.md)。
