### ISSUE TITLE
Some GPUs are not working properly in multi-gpu pod

### ISSUE THREAD

**Issue by hejm37** [iiisthu/gpupool#19]
Hi, I have a multi-gpu pod (8 gpus), but some gpus are not working properly. Here is my config
```yaml
          resources: # 描述申请的机器资源
            limits:
              cpu: 16 # 最大CPU
              memory: 32Gi # 最大内存
              virtaitech.com/gpu: 8 # 最大GPU数目
            requests:
              cpu: 16 # 最小需要的CPU数目 （如果目前资源不够，就放弃启动）
              memory: 24Gi # 最小需要申请的内存的数目（如果目前资源不够，就放弃启动）
              virtaitech.com/gpu: 8 # 最小需要的GPU数目
          env:
            - name: ORION_GMEM
              value: "11000" # 每张显卡的显存，单位为M
            - name: ORION_RATIO
              value: "100"
            - name: ORION_VGPU
              value: "8"
            - name: ORION_RESERVED
              value: "0"
            - name: ORION_CROSS_NODE
              value: "1"
            - name: ORION_GROUP_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
```
Here is my test example (see below code block). I try to create a tensor of 3GB in each GPU, but some of the attempts failed (gpu0, gpu1, gpu4, gpu5) while others succeed (gpu2, gpu3, gpu6, gpu7).
```shell
>>> import torch; torch.cuda.device_count()
VirtaiTech Resource. Build-20201209_195723-4f0a3fd
8
>>> torch.zeros((800000000), device=torch.device('cuda:0'))
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0')
>>> a1 = torch.zeros((800000000), device=torch.device('cuda:1'))
>>> a2 = torch.zeros((800000000), device=torch.device('cuda:2'))
2021-01-21 12:42:14 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
2021-01-21 12:42:14 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA out of memory. Tried to allocate 2.98 GiB (GPU 2; 10.74 GiB total capacity; 0 bytes already allocated; 10.58 GiB free; 0 bytes reserved in total by PyTorch)
>>> a3 = torch.zeros((800000000), device=torch.device('cuda:3'))
2021-01-21 12:42:19 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
2021-01-21 12:42:19 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA out of memory. Tried to allocate 2.98 GiB (GPU 3; 10.74 GiB total capacity; 0 bytes already allocated; 10.58 GiB free; 0 bytes reserved in total by PyTorch)
>>> a4 = torch.zeros((800000000), device=torch.device('cuda:4'))
>>> a5 = torch.zeros((800000000), device=torch.device('cuda:5'))
>>> a6 = torch.zeros((800000000), device=torch.device('cuda:6'))
2021-01-21 12:42:36 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
2021-01-21 12:42:36 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA out of memory. Tried to allocate 2.98 GiB (GPU 6; 10.74 GiB total capacity; 0 bytes already allocated; 10.58 GiB free; 0 bytes reserved in total by PyTorch)
>>> a7 = torch.zeros((800000000), device=torch.device('cuda:7'))
2021-01-21 12:42:41 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
2021-01-21 12:42:41 [ERROR] cuMemAlloc(): CUDA error code <2, 0>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA out of memory. Tried to allocate 2.98 GiB (GPU 7; 10.74 GiB total capacity; 0 bytes already allocated; 10.58 GiB free; 0 bytes reserved in total by PyTorch)
```

**Comment by hejm37** [comment]
Look like the physical GPUs (gpu2, gpu3, gpu6, gpu7) are occupied by other programs.
